<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!-- PDF 统一学生格式 -->
  <xs:complexType name="studentType">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="sex" type="xs:string"/>
      <xs:element name="major" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <!-- PDF 统一课程格式 -->
  <xs:complexType name="classType">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="time" type="xs:unsignedByte"/>
      <xs:element name="score" type="xs:unsignedByte"/>
      <xs:element name="teacher" type="xs:string"/>
      <xs:element name="location" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <!-- PDF 统一选课格式 -->
  <xs:complexType name="choiceType">
    <xs:sequence>
      <xs:element name="sid" type="xs:string"/>
      <xs:element name="cid" type="xs:string"/>
      <xs:element name="score" type="xs:unsignedByte"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" type="studentType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="classes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="class" type="classType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="choices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="choice" type="choiceType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
